version: '3.8'

services:
  # Baza danych PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: flask_postgres
    environment:
      POSTGRES_USER: flaskapp
      POSTGRES_PASSWORD: FlaskSecurePass2024
      POSTGRES_DB: flask_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flaskapp"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aplikacja Flask
  web:
    build: .
    container_name: flask_app
    environment:
      DATABASE_URL: postgresql://flaskapp:FlaskSecurePass2024@db:5432/flask_app
      SECRET_KEY: MyFlaskSecretKey2024XYZ123ABC
      FLASK_ENV: production
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
