# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: httpd-backend
#   labels:
#     app: httpd-backend
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: httpd-backend
#   template:
#     metadata:
#       labels:
#         app: httpd-backend
#     spec:
#       containers:
#         - name: httpd
#           # image: httpd:2.4-alpine
#           image: maggieblue/vulnerable-project:latest
#           ports:
#             - containerPort: 5000
#               name: http
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: httpd-backend-service
# spec:
#   selector:
#     app: httpd-backend
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 5000
#   type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: flask-backend-service
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 2  # dla load balancingu
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: maggieblue/vulnerable-project:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: postgresql://flaskapp:FlaskSecurePass2024@db:5432/flask_app
        - name: SECRET_KEY
          value: MyFlaskSecretKey2024XYZ123ABC
        - name: FLASK_ENV
          value: production
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: flask_app
        - name: POSTGRES_USER
          value: flaskapp
        - name: POSTGRES_PASSWORD
          value: FlaskSecurePass2024
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc