apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80 default_server;
        server_name vulnerable-webapp.switzerlandnorth.cloudapp.azure.com www.vulnerable-webapp.switzerlandnorth.cloudapp.azure.com;
        
        # return 301 https://$server_name$request_uri;

        location / {
            proxy_pass http://flask-backend-service:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    server {
        listen 443 ssl;
        server_name vulnerable-webapp.switzerlandnorth.cloudapp.azure.com www.vulnerable-webapp.switzerlandnorth.cloudapp.azure.com;

        ssl_certificate     /etc/nginx/ssl/certificate.crt;
        ssl_certificate_key /etc/nginx/ssl/private.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            # Proxy do httpd backend service w klastrze
            proxy_pass http://flask-backend-service:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }