apiVersion: v1
kind: Service
metadata:
  name: vulnerablewebapp-service
spec:
  selector:
    app: vulnerablewebapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
