name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Check out code
  
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      run: cd app
      with:
        image: maggieblue/vulnerable-project
        tags: v1, latest
        registry: docker.io
        directory: app
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
